services:
  - type: web
    name: wort-wirbel
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
