services:
  - type: web
    name: wort-wirbel
    env: static
    buildCommand: |
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter config --no-analytics
      flutter doctor --android-licenses || true
      flutter pub get
      flutter build web --release
    staticPublishPath: build/web
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
