name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  # Wait for lint and test jobs to complete successfully
  lint:
    name: Run Linting
    uses: ./.github/workflows/lint.yml
    
  test:
    name: Run Tests  
    uses: ./.github/workflows/test.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build-and-deploy:
    name: Build and Deploy to Render
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        channel: 'stable'
        cache: true
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build web app
      run: flutter build web --release
      
    - name: Deploy to Render
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true
