name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  # Wait for lint and test jobs to complete successfully
  lint:
    name: Run Linting
    uses: ./.github/workflows/lint.yml
    
  test:
    name: Run Tests  
    uses: ./.github/workflows/test.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  deploy-render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
    - name: Trigger Render Deploy
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true
